name: non_local_detector
channels:
- defaults
- conda-forge
- edeno
dependencies:
- numpy
- scipy
- jax
- networkx
- xarray
- scikit-learn
- patsy
- tqdm
- track_linearization
- replay_trajectory_classification
- matplotlib
- seaborn
- ipython
- black
- pytest
- pytest-cov